services:
  athenas-db:
    image: postgres:16.2
    container_name: athenas-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: athenas
      POSTGRES_PASSWORD: athenas
      POSTGRES_DB: athenas
    #volumes:
     # - .docker/athenas-db-data:/var/lib/postgresql/data
    networks:
      - athenas-network
    deploy:
        resources:
            limits:
                cpus: '0.2'
                memory: 256M

  rabbitmq: 
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq-athenas
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
        resources:
            limits:
                cpus: '0.2'
                memory: 128M

networks:
  athenas-network:
    #driver: bridge 
