services:
  athenas-db:
    image: postgres:16.2
    container_name: athenas-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: athenas
      POSTGRES_PASSWORD: athenas
      POSTGRES_DB: athenas
    #volumes:
     # - .docker/athenas-db-data:/var/lib/postgresql/data
    networks:
      - athenas-network
    deploy:
        resources:
            limits:
                cpus: '0.2'
                memory: 256M

  rabbitmq: 
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq-athenas
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
        resources:
            limits:
                cpus: '0.2'
                memory: 128M


  mailhog: 
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"



  # cockroachdb:
  #   image: cockroachdb/cockroach:v21.1.0
  #   container_name: cockroachdb-athenas
  #   command: start-single-node --insecure
  #   ports:
  #     - "26257:26257"
  #     - "9000:8080"

networks:
  athenas-network:
    #driver: bridge 
