version: "3.8"

services:
  athenas-db:
    image: postgres:16.2
    container_name: athenas-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: athenas
      POSTGRES_PASSWORD: athenas
      POSTGRES_DB: athenas
    volumes:
      - .docker/athenas-db-data:/var/lib/postgresql/data
  rabbitmq: 
    image: rabbitmq:3.13.2-management-alpine 
    container_name: athenas-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"  