name: Run Tests CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs: 

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


  test:
  runs-on: ubuntu-latest
  steps: 
    - uses: actions/checkout@v3
    - name: Test with vitest
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"
    - run: pnpm install
    - run: pnpm test